package AutoTrack;


/**
* AutoTrack/MileageProviderOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from autotrack.idl
* vendredi 5 décembre 2025 18 h 34 WAT
*/

public interface MileageProviderOperations 
{
  String getMileage ();
} // interface MileageProviderOperations
