package AutoTrack;


/**
* AutoTrack/MileageProviderHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from autotrack.idl
* vendredi 5 décembre 2025 18 h 34 WAT
*/

abstract public class MileageProviderHelper
{
  private static String  _id = "IDL:AutoTrack/MileageProvider:1.0";

  public static void insert (org.omg.CORBA.Any a, AutoTrack.MileageProvider that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static AutoTrack.MileageProvider extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (AutoTrack.MileageProviderHelper.id (), "MileageProvider");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static AutoTrack.MileageProvider read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_MileageProviderStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, AutoTrack.MileageProvider value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static AutoTrack.MileageProvider narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof AutoTrack.MileageProvider)
      return (AutoTrack.MileageProvider)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      AutoTrack._MileageProviderStub stub = new AutoTrack._MileageProviderStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static AutoTrack.MileageProvider unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof AutoTrack.MileageProvider)
      return (AutoTrack.MileageProvider)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      AutoTrack._MileageProviderStub stub = new AutoTrack._MileageProviderStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
