package AutoTrack;

/**
* AutoTrack/MileageProviderHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from autotrack.idl
* vendredi 5 décembre 2025 18 h 34 WAT
*/

public final class MileageProviderHolder implements org.omg.CORBA.portable.Streamable
{
  public AutoTrack.MileageProvider value = null;

  public MileageProviderHolder ()
  {
  }

  public MileageProviderHolder (AutoTrack.MileageProvider initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AutoTrack.MileageProviderHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AutoTrack.MileageProviderHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AutoTrack.MileageProviderHelper.type ();
  }

}
