package AutoTrack;


/**
* AutoTrack/MileageProviderPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from autotrack.idl
* vendredi 5 décembre 2025 18 h 34 WAT
*/

public abstract class MileageProviderPOA extends org.omg.PortableServer.Servant
 implements AutoTrack.MileageProviderOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getMileage", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // AutoTrack/MileageProvider/getMileage
       {
         String $result = null;
         $result = this.getMileage ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:AutoTrack/MileageProvider:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public MileageProvider _this() 
  {
    return MileageProviderHelper.narrow(
    super._this_object());
  }

  public MileageProvider _this(org.omg.CORBA.ORB orb) 
  {
    return MileageProviderHelper.narrow(
    super._this_object(orb));
  }


} // class MileageProviderPOA
